{% set version = "4.6" %}
{% set sha256 = "beff6acf1c7838cc722714d143a64e706e2fd3bd1e00d3cd75152f596b09bb9e" %}

package:
  name: sed
  version: {{ version }}

source:
  fn: sed-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/sed/sed-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - gettext >=0.19.2  # [osx]
  run:
    - gettext >=0.19.2  # [osx]

test:
  commands:
    - test -f "${PREFIX}/bin/sed"
    - sed --version

about:
  home: https://www.gnu.org/software/sed/
  license: GPL-3
  summary: 'sed (stream editor) is a non-interactive command-line text editor.'

extra:
  recipe-maintainers:
    - tfors
