{% set version = "4.9" %}

package:
  name: sed
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/sed/sed-{{ version }}.tar.xz
  sha256: 6e226b732e1cd739464ad6862bd1a1aba42d7982922da7a53519631d24975181

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - gettext      # [osx]

test:
  commands:
    - test -f "${PREFIX}/bin/sed"
    - sed --version

about:
  home: https://www.gnu.org/software/sed/
  license: GPL-3.0-only
  license_file: COPYING
  summary: sed (stream editor) is a non-interactive command-line text editor.

extra:
  recipe-maintainers:
    - tfors
    - hmaarrfk
