{% set version = "4.5" %}
{% set sha256 = "7aad73c8839c2bdadca9476f884d2953cdace9567ecd0d90f9959f229d146b40" %}

package:
  name: sed
  version: {{ version }}

source:
  fn: sed-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/sed/sed-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gettext >=0.19.2  # [osx]
  run:
    - gettext >=0.19.2  # [osx]

test:
  commands:
    - test -f "${PREFIX}/bin/sed"
    - sed --version

about:
  home: https://www.gnu.org/software/sed/
  license: GPL-3
  summary: 'sed (stream editor) is a non-interactive command-line text editor.'

extra:
  recipe-maintainers:
    - tfors
